var routes = [
  {
    path: "/dashboard",
    name: "Admin Dashboard",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "",
  },
  {
    path: "/searchstudent",
    name: "User Search",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "",
  },
  {
    path: "/Quiz",
    name: "Quiz",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "",
  },
  {
    path: "/Task",
    name: "Tasks",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "",
  },
  {
    path: "/studentDetails",
    name: "User Search",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "d-none",
  },
  {
    path: "/taskDetails",
    name: "Task Details",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "d-none",
  },
  {
    path: "/quizDetails",
    name: "Quiz Details",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "d-none",
  },
  {
    path: "/classroomDetail",
    name: "Classroom Detail",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "d-none",
  },
  {
    path: "/classroom",
    name: "Classroom",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "",
  },
  {
    path: "/course",
    name: "Classroom",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "d-none",
  },
  {
    path: "/CreateQuiz",
    name: "Create Quiz",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "d-none",
  },
  {
    path: "/createClassroom",
    name: "Create Classroom",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "",
  },
  {
    path: "/editclassroom",
    name: "Edit Classroom",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "d-none",
  },
  {
    path: "/ClassroomDetails",
    name: "Classroom Details",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "d-none",
  },
  {
    path: "/createTask",
    name: "Create Task",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "d-none",
  },
  {
    path: "/EditQuiz",
    name: "Edit Quiz",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "d-none",
  },
  {
    path: "/courseclass",
    name: "Create Courses",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "",
  },
  {
    path: "/CourseDetail",
    name: "Course Details",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "",
  },
  {
    path: "/CourseRead",
    name: "Course Read",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "d-none",
  },
  {
    path: "/mentors",
    name: "Mentors",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "",
  },
  // {
  //   path: "/wp/admin",
  //   name: "Admin Login",
  //   icon: "ni ni-tv-2 text-primary",
  //   layout: "/auth",
  //   class: "",
  // },
  // {
  //   path: "/Workshopdetails",
  //   name: "Workshop",
  //   icon: "ni ni-tv-2 text-primary",
  //   layout: "/admin",
  //   class: "",
  // },
  {
    path: "/Createworkshop",
    name: "Create Workshop",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "",
  },
  {
    path: "/Workshops",
    name: "Workshops",
    icon: "ni ni-tv-2 text-primary",
    layout: "/admin",
    class: "",
  },
];
export default routes;
