var wRoutes = [
  {
    path: "/Workshopdetails",
    name: "Workshop Details",
    icon: "ni ni-tv-2 text-primary",
    layout: "/workshop",
    class: "",
  },
  {
    path: "/WorkshopCreatequiz",
    name: "Create Quiz",
    icon: "ni ni-tv-2 text-primary",
    layout: "/workshop",
    class: "",
  },
  {
    path: "/WorkshopCreateTask",
    name: "Create Task",
    icon: "ni ni-tv-2 text-primary",
    // component: WQuizDetails,
    layout: "/workshop",
    class: "",
  },
  {
    path: "/WorkshopTask",
    name: "Tasks",
    icon: "ni ni-tv-2 text-primary",
    // component: WQuizDetails,
    layout: "/workshop",
    class: "",
  },
  {
    path: "/Workshopquiz",
    name: "Quizes",
    icon: "ni ni-tv-2 text-primary",
    // component: WQuizDetails,
    layout: "/workshop",
    class: "",
  },
  {
    path: "/Calender",
    name: "Calender",
    icon: "ni ni-tv-2 text-primary",
    // component: WQuizDetails,
    layout: "/workshop",
    class: "",
  },
  {
    path: "/Jitsi",
    name: "Jitsi",
    icon: "ni ni-tv-2 text-primary",
    // component: WQuizDetails,
    layout: "/workshop",
    class: "",
  },
  {
    path: "/Schedule",
    name: "Schedule Meet",
    icon: "ni ni-tv-2 text-primary",
    // component: WQuizDetails,
    layout: "/workshop",
    class: "",
  },
];
export default wRoutes;
